Repository MEN-Mikro-Elektronik/13MD05-90, pull requests merged in 2023-04, with the labels that each got.

#301 Pull Request to use tag date instead of last commit date in STAMPED_VERSION
  INSTALL.sh
Labels: enhancement

#302 Pull Request to update changelog for release 02_05
  13MD05-90_changelog.md
Labels: requirement

#307 Update fpga_load binary
  MDISforLinux/BIN/fpga_load
Labels: enhancement, requirement

#309 Scan mem type
  MDISforLinux/SCAN_SYSTEM_SCRIPTS/xml_parser.sh
  MDISforLinux/scan_system.sh
Labels: enhancement
